apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myapp
spec:
  host: myapp
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 3
        http:
          http1MaxPendingRequests: 50
          maxRequestsPerConnection: 3
  - name: v2
    labels:
      version: v2